name: CI
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        version: 12
   - name: Set env to staging
      if: endsWith(github.ref, '/develop')
      run: |
        echo "::set-env name=ENVIRONMENT::staging"
    - name: check env for staging
      run: |
        echo $ENVIRONMENT
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: |
        echo "::set-env name=ENVIRONMENT::production" 
    - name: check env for production
      run: |
        echo $ENVIRONMENT

  