name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 
      uses: actions/setup-node@master
      with:
        version: 12
    - name: install
      run: yarn install
    - name: Set up NPM authentication
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_PERSONAL_TOKEN }}" >> .npmrc
        echo "registry=https://npm.pkg.github.com" >> .npmrc  
    - name: Configure CI Git User
      run: |
        git remote rm origin
        git remote add origin "https://gyl9196:$GITHUB_PAT@github.com/gyl9196/ui-components.git"
        git fetch
        git checkout master
        git config --global user.email nielgong@gmail.com
        git config --global user.name gyl9196
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    - name: checkChanged
      run: yarn checkChanged