name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@feature/test
    - name: check code change
      run: git diff --name-only master packages/ | grep / | awk 'BEGIN {FS="/"} {print $2}' | uniq 
    - name: show variables
      run: echo $GITHUB_REF	$GITHUB_REPOSITORY $GITHUB_WORKSPACE $GITHUB_SHA $GITHUB_REF