name: CI
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [12]
    steps:
    - name: Use Node.js 
      uses: actions/setup-node@master
      with:
        version: 12
    - name: Configure CI Git User
      run: |
        git config --global user.email gyl91962010@gmail.com
        git config --global user.name test
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        git pull
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_PERSONAL_TOKEN }}" >> .npmrc
        echo "registry=https://npm.pkg.github.com" >> .npmrc 
        yarn install
        yarn publishmodules
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         #     git remote rm origin
    #     git remote add origin "https://gyl9196:$GITHUB_PAT@github.com/gyl9196/ui-components.git"
    #     git fetch
    #     git checkout master